name: CampGo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  image: ^4.1.7
  path_provider: ^2.1.2

  # Core dependencies - Đảm bảo phiên bản phù hợp cho iOS
  curved_navigation_bar: ^1.0.6
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.0.0
  model_viewer_plus: ^1.9.0
  flutter_3d_controller: ^2.0.2
  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2
  dio: ^5.3.2
  crypto: ^3.0.3
  path: ^1.8.3
  pin_code_fields: ^8.0.0

  # State management và utilities
  provider: ^6.0.0
  intl: ^0.19.0
  sqflite_common_ffi: ^2.3.3+1
  flutter_stripe: ^11.2.0
  vector_math: ^2.1.4
  lottie: ^3.2.0
  tflite_flutter: ^0.11.0

  # Thêm các package này để làm việc với JSON tốt hơn
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  fake_async: ^1.3.1

  # Added from the code block
  dropdown_search: ^5.0.6
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8  # Cần thiết để generate code

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/StartNow.jpg
    - assets/images/img1.png
    # - assets/data/Notification.json
    - assets/data/Product.json
    - assets/data/Categories.json
    # - assets/data/Review.json
    - assets/data/Login.json
    - assets/data/SignUp.json
    - assets/data/Cart.json
    - assets/data/CheckOut.json
    - assets/data/Wishlist.json
    - assets/data/UserProfile.json
    - assets/data/AddressUser.json