import 'dart:convert';
import 'package:http/http.dart' as http;

class AddressService {
  static const String _baseUrl = 'https://online-gateway.ghn.vn/api/v1';
  static const String _token = 'Token 5c3c3a3c-3c3a-3c3a-3c3a-3c3a3c3a3c3a'; // Token mẫu, bạn cần đăng ký để lấy token thật

  // Lấy danh sách tỉnh/thành phố
  Future<List<String>> getProvinces() async {
    return [
      'Hà Nội',
      'TP Hồ Chí Minh',
      'Đà Nẵng',
      'Hải Phòng',
      'Cần Thơ',
      'Bình Dương',
      'Đồng Nai',
      'Bà Rịa - Vũng Tàu',
      'Hải Dương',
      'Thái Bình',
      'Nam Định',
      'Ninh Bình',
      'Thanh Hóa',
      'Nghệ An',
      'Hà Tĩnh',
      'Quảng Bình',
      'Quảng Trị',
      'Thừa Thiên Huế',
      'Quảng Nam',
      'Quảng Ngãi',
      'Bình Định',
      'Phú Yên',
      'Khánh Hòa',
      'Ninh Thuận',
      'Bình Thuận',
      'Kon Tum',
      'Gia Lai',
      'Đắk Lắk',
      'Đắk Nông',
      'Lâm Đồng',
      'Bình Phước',
      'Tây Ninh',
      'Bến Tre',
      'Trà Vinh',
      'Vĩnh Long',
      'Đồng Tháp',
      'An Giang',
      'Kiên Giang',
      'Cà Mau',
      'Bạc Liêu',
      'Sóc Trăng',
    ];
  }

  // Lấy danh sách quận/huyện theo tỉnh/thành phố
  Future<List<String>> getDistricts(String provinceName) async {
    switch (provinceName) {
      case 'Hà Nội':
        return [
          'Ba Đình',
          'Hoàn Kiếm',
          'Hai Bà Trưng',
          'Đống Đa',
          'Cầu Giấy',
          'Thanh Xuân',
          'Hoàng Mai',
          'Long Biên',
          'Tây Hồ',
          'Nam Từ Liêm',
          'Bắc Từ Liêm',
          'Hà Đông',
          'Sơn Tây',
          'Ba Vì',
          'Chương Mỹ',
          'Đan Phượng',
          'Đông Anh',
          'Gia Lâm',
          'Hoài Đức',
          'Mê Linh',
          'Mỹ Đức',
          'Phú Xuyên',
          'Phúc Thọ',
          'Quốc Oai',
          'Sóc Sơn',
          'Thạch Thất',
          'Thanh Oai',
          'Thanh Trì',
          'Thường Tín',
          'Ứng Hòa',
        ];
      case 'TP Hồ Chí Minh':
        return [
          'Quận 1',
          'Quận 2',
          'Quận 3',
          'Quận 4',
          'Quận 5',
          'Quận 6',
          'Quận 7',
          'Quận 8',
          'Quận 9',
          'Quận 10',
          'Quận 11',
          'Quận 12',
          'Quận Bình Thạnh',
          'Quận Bình Tân',
          'Quận Gò Vấp',
          'Quận Phú Nhuận',
          'Quận Tân Bình',
          'Quận Tân Phú',
          'Quận Thủ Đức',
          'Huyện Bình Chánh',
          'Huyện Cần Giờ',
          'Huyện Củ Chi',
          'Huyện Hóc Môn',
          'Huyện Nhà Bè',
        ];
      case 'Đà Nẵng':
        return [
          'Quận Hải Châu',
          'Quận Thanh Khê',
          'Quận Sơn Trà',
          'Quận Ngũ Hành Sơn',
          'Quận Liên Chiểu',
          'Quận Cẩm Lệ',
          'Huyện Hòa Vang',
          'Huyện Hoàng Sa',
        ];
      case 'Hải Phòng':
        return [
          'Quận Hồng Bàng',
          'Quận Ngô Quyền',
          'Quận Lê Chân',
          'Quận Hải An',
          'Quận Kiến An',
          'Quận Đồ Sơn',
          'Quận Dương Kinh',
          'Huyện Thủy Nguyên',
          'Huyện An Dương',
          'Huyện An Lão',
          'Huyện Kiến Thụy',
          'Huyện Tiên Lãng',
          'Huyện Vĩnh Bảo',
          'Huyện Cát Hải',
          'Huyện Bạch Long Vĩ',
        ];
      case 'Cần Thơ':
        return [
          'Quận Ninh Kiều',
          'Quận Bình Thủy',
          'Quận Cái Răng',
          'Quận Ô Môn',
          'Quận Thốt Nốt',
          'Huyện Phong Điền',
          'Huyện Cờ Đỏ',
          'Huyện Thới Lai',
          'Huyện Vĩnh Thạnh',
        ];
      case 'Bình Dương':
        return [
          'Thành phố Thủ Dầu Một',
          'Thành phố Dĩ An',
          'Thành phố Thuận An',
          'Thành phố Bến Cát',
          'Thành phố Tân Uyên',
          'Huyện Bàu Bàng',
          'Huyện Bắc Tân Uyên',
          'Huyện Dầu Tiếng',
          'Huyện Phú Giáo',
        ];
      case 'Đồng Nai':
        return [
          'Thành phố Biên Hòa',
          'Thành phố Long Khánh',
          'Huyện Tân Phú',
          'Huyện Vĩnh Cửu',
          'Huyện Định Quán',
          'Huyện Trảng Bom',
          'Huyện Thống Nhất',
          'Huyện Cẩm Mỹ',
          'Huyện Long Thành',
          'Huyện Xuân Lộc',
          'Huyện Nhơn Trạch',
        ];
      default:
        return [];
    }
  }

  // Lấy danh sách phường/xã theo quận/huyện
  Future<List<String>> getWards(String districtName) async {
    switch (districtName) {
      case 'Quận 1':
        return [
          'Phường Bến Nghé',
          'Phường Bến Thành',
          'Phường Cầu Kho',
          'Phường Cầu Ông Lãnh',
          'Phường Cô Giang',
          'Phường Đa Kao',
          'Phường Nguyễn Cư Trinh',
          'Phường Nguyễn Thái Bình',
          'Phường Phạm Ngũ Lão',
          'Phường Tân Định',
        ];
      case 'Quận Hải Châu':
        return [
          'Phường Hải Châu 1',
          'Phường Hải Châu 2',
          'Phường Hòa Cường Bắc',
          'Phường Hòa Cường Nam',
          'Phường Hòa Thuận Đông',
          'Phường Hòa Thuận Tây',
          'Phường Nam Dương',
          'Phường Phước Ninh',
          'Phường Thạch Thang',
          'Phường Thanh Bình',
          'Phường Thuận Phước',
        ];
      case 'Ba Đình':
        return [
          'Phường Phúc Xá',
          'Phường Trúc Bạch',
          'Phường Vĩnh Phúc',
          'Phường Cống Vị',
          'Phường Liễu Giai',
          'Phường Nguyễn Trung Trực',
          'Phường Quán Thánh',
          'Phường Ngọc Hà',
          'Phường Điện Biên',
          'Phường Đội Cấn',
          'Phường Ngọc Khánh',
          'Phường Kim Mã',
          'Phường Giảng Võ',
          'Phường Thành Công',
        ];
      case 'Quận Ninh Kiều':
        return [
          'Phường An Bình',
          'Phường An Cư',
          'Phường An Hòa',
          'Phường An Khánh',
          'Phường An Nghiệp',
          'Phường An Phú',
          'Phường Cái Khế',
          'Phường Hưng Lợi',
          'Phường Tân An',
          'Phường Thới Bình',
          'Phường Xuân Khánh',
        ];
      case 'Quận Hồng Bàng':
        return [
          'Phường Hạ Lý',
          'Phường Hoàng Văn Thụ',
          'Phường Hùng Vương',
          'Phường Minh Khai',
          'Phường Phạm Hồng Thái',
          'Phường Phan Bội Châu',
          'Phường Quán Toan',
          'Phường Quang Trung',
          'Phường Sở Dầu',
          'Phường Thượng Lý',
          'Phường Trại Chuối',
        ];
      case 'Quận 2':
        return [
          'Phường An Khánh',
          'Phường An Lợi Đông',
          'Phường An Phú',
          'Phường Bình An',
          'Phường Bình Khánh',
          'Phường Bình Trưng Đông',
          'Phường Bình Trưng Tây',
          'Phường Cát Lái',
          'Phường Thạnh Mỹ Lợi',
          'Phường Thảo Điền',
          'Phường Thủ Thiêm',
        ];
      case 'Quận 3':
        return [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
        ];
      case 'Quận Bình Thạnh':
        return [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 17',
          'Phường 19',
          'Phường 21',
          'Phường 22',
          'Phường 24',
          'Phường 25',
          'Phường 26',
          'Phường 27',
          'Phường 28',
        ];
      case 'Thành phố Thủ Dầu Một':
        return [
          'Phường Chánh Mỹ',
          'Phường Chánh Nghĩa',
          'Phường Định Hòa',
          'Phường Hiệp An',
          'Phường Hiệp Thành',
          'Phường Hòa Phú',
          'Phường Phú Cường',
          'Phường Phú Hòa',
          'Phường Phú Lợi',
          'Phường Phú Mỹ',
          'Phường Phú Tân',
          'Phường Phú Thọ',
          'Phường Tân An',
          'Phường Tương Bình Hiệp',
        ];
      case 'Thành phố Biên Hòa':
        return [
          'Phường An Bình',
          'Phường Bình Đa',
          'Phường Bửu Hòa',
          'Phường Bửu Long',
          'Phường Hiệp Hòa',
          'Phường Hóa An',
          'Phường Hòa Bình',
          'Phường Long Bình',
          'Phường Long Bình Tân',
          'Phường Quang Vinh',
          'Phường Quyết Thắng',
          'Phường Tam Hiệp',
          'Phường Tam Hòa',
          'Phường Tân Biên',
          'Phường Tân Hạnh',
          'Phường Tân Hiệp',
          'Phường Tân Hòa',
          'Phường Tân Mai',
          'Phường Tân Phong',
          'Phường Tân Tiến',
          'Phường Tân Vạn',
          'Phường Thanh Bình',
          'Phường Thống Nhất',
          'Phường Trảng Dài',
          'Phường Trung Dũng',
        ];
      case 'Quận Thanh Khê':
        return [
          'Phường An Khê',
          'Phường Chính Gián',
          'Phường Hòa Khê',
          'Phường Tam Thuận',
          'Phường Tân Chính',
          'Phường Thạc Gián',
          'Phường Thanh Khê Đông',
          'Phường Thanh Khê Tây',
          'Phường Vĩnh Trung',
          'Phường Xuân Hà',
        ];
      case 'Quận Sơn Trà':
        return [
          'Phường An Hải Bắc',
          'Phường An Hải Đông',
          'Phường An Hải Nam',
          'Phường An Hải Tây',
          'Phường Mân Thái',
          'Phường Nại Hiên Đông',
          'Phường Phước Mỹ',
          'Phường Thọ Quang',
        ];
      case 'Quận Ngũ Hành Sơn':
        return [
          'Phường Hòa Hải',
          'Phường Hòa Quý',
          'Phường Khuê Mỹ',
          'Phường Mỹ An',
        ];
      case 'Quận Liên Chiểu':
        return [
          'Phường Hòa Hiệp Bắc',
          'Phường Hòa Hiệp Nam',
          'Phường Hòa Khánh Bắc',
          'Phường Hòa Khánh Nam',
          'Phường Hòa Minh',
        ];
      case 'Quận Cẩm Lệ':
        return [
          'Phường Hòa An',
          'Phường Hòa Phát',
          'Phường Hòa Thọ Đông',
          'Phường Hòa Thọ Tây',
          'Phường Hòa Xuân',
          'Phường Khuê Trung',
        ];
      case 'Hoàn Kiếm':
        return [
          'Phường Chương Dương',
          'Phường Cửa Đông',
          'Phường Cửa Nam',
          'Phường Đồng Xuân',
          'Phường Hàng Bạc',
          'Phường Hàng Bài',
          'Phường Hàng Bồ',
          'Phường Hàng Bông',
          'Phường Hàng Buồm',
          'Phường Hàng Đào',
          'Phường Hàng Gai',
          'Phường Hàng Mã',
          'Phường Hàng Trống',
          'Phường Lý Thái Tổ',
          'Phường Phan Chu Trinh',
          'Phường Phúc Tân',
          'Phường Trần Hưng Đạo',
          'Phường Tràng Tiền',
        ];
      case 'Hai Bà Trưng':
        return [
          'Phường Bách Khoa',
          'Phường Bạch Đằng',
          'Phường Bạch Mai',
          'Phường Bùi Thị Xuân',
          'Phường Cầu Dền',
          'Phường Đống Mác',
          'Phường Đồng Nhân',
          'Phường Đồng Tâm',
          'Phường Lê Đại Hành',
          'Phường Minh Khai',
          'Phường Ngô Thì Nhậm',
          'Phường Nguyễn Du',
          'Phường Phạm Đình Hổ',
          'Phường Phố Huế',
          'Phường Quỳnh Lôi',
          'Phường Quỳnh Mai',
          'Phường Thanh Lương',
          'Phường Thanh Nhàn',
          'Phường Trương Định',
          'Phường Vĩnh Tuy',
        ];
      case 'Đống Đa':
        return [
          'Phường Cát Linh',
          'Phường Hàng Bột',
          'Phường Khâm Thiên',
          'Phường Khương Thượng',
          'Phường Kim Liên',
          'Phường Láng Hạ',
          'Phường Láng Thượng',
          'Phường Nam Đồng',
          'Phường Ngã Tư Sở',
          'Phường Ô Chợ Dừa',
          'Phường Phương Liên',
          'Phường Phương Mai',
          'Phường Quang Trung',
          'Phường Quốc Tử Giám',
          'Phường Thịnh Quang',
          'Phường Thổ Quan',
          'Phường Trung Liệt',
          'Phường Trung Phụng',
          'Phường Trung Tự',
          'Phường Văn Chương',
          'Phường Văn Miếu',
        ];
      case 'Cầu Giấy':
        return [
          'Phường Dịch Vọng',
          'Phường Dịch Vọng Hậu',
          'Phường Mai Dịch',
          'Phường Nghĩa Đô',
          'Phường Nghĩa Tân',
          'Phường Quan Hoa',
          'Phường Trung Hòa',
          'Phường Yên Hòa',
        ];
      case 'Thanh Xuân':
        return [
          'Phường Hạ Đình',
          'Phường Khương Đình',
          'Phường Khương Mai',
          'Phường Khương Trung',
          'Phường Kim Giang',
          'Phường Nhân Chính',
          'Phường Phương Liệt',
          'Phường Thanh Xuân Bắc',
          'Phường Thanh Xuân Nam',
          'Phường Thanh Xuân Trung',
          'Phường Thượng Đình',
        ];
      case 'Hoàng Mai':
        return [
          'Phường Đại Kim',
          'Phường Định Công',
          'Phường Giáp Bát',
          'Phường Hoàng Liệt',
          'Phường Hoàng Văn Thụ',
          'Phường Lĩnh Nam',
          'Phường Mai Động',
          'Phường Tân Mai',
          'Phường Thanh Trì',
          'Phường Thịnh Liệt',
          'Phường Trần Phú',
          'Phường Tương Mai',
          'Phường Vĩnh Hưng',
          'Phường Yên Sở',
        ];
      case 'Long Biên':
        return [
          'Phường Bồ Đề',
          'Phường Cự Khối',
          'Phường Đức Giang',
          'Phường Gia Thụy',
          'Phường Giang Biên',
          'Phường Long Biên',
          'Phường Ngọc Lâm',
          'Phường Ngọc Thụy',
          'Phường Phúc Đồng',
          'Phường Phúc Lợi',
          'Phường Sài Đồng',
          'Phường Thạch Bàn',
          'Phường Thượng Thanh',
          'Phường Việt Hưng',
        ];
      case 'Tây Hồ':
        return [
          'Phường Bưởi',
          'Phường Nhật Tân',
          'Phường Phú Thượng',
          'Phường Quảng An',
          'Phường Thụy Khuê',
          'Phường Tứ Liên',
          'Phường Xuân La',
          'Phường Yên Phụ',
        ];
      case 'Nam Từ Liêm':
        return [
          'Phường Cầu Diễn',
          'Phường Đại Mỗ',
          'Phường Mễ Trì',
          'Phường Mỹ Đình 1',
          'Phường Mỹ Đình 2',
          'Phường Phú Đô',
          'Phường Phương Canh',
          'Phường Tây Mỗ',
          'Phường Trung Văn',
          'Phường Xuân Phương',
        ];
      case 'Bắc Từ Liêm':
        return [
          'Phường Cổ Nhuế 1',
          'Phường Cổ Nhuế 2',
          'Phường Đông Ngạc',
          'Phường Đức Thắng',
          'Phường Liên Mạc',
          'Phường Minh Khai',
          'Phường Phú Diễn',
          'Phường Phúc Diễn',
          'Phường Tả Thanh Oai',
          'Phường Tam Hiệp',
          'Phường Tân Triều',
          'Phường Thanh Liệt',
          'Phường Tứ Hiệp',
          'Phường Vạn Phúc',
          'Phường Vĩnh Quỳnh',
          'Phường Yên Mỹ',
        ];
      case 'Hà Đông':
        return [
          'Phường Biên Giang',
          'Phường Đồng Mai',
          'Phường Dương Nội',
          'Phường Hà Cầu',
          'Phường Kiến Hưng',
          'Phường La Khê',
          'Phường Mộ Lao',
          'Phường Nguyễn Trãi',
          'Phường Phú La',
          'Phường Phú Lãm',
          'Phường Phú Lương',
          'Phường Phúc La',
          'Phường Quang Trung',
          'Phường Vạn Phúc',
          'Phường Văn Quán',
          'Phường Yên Nghĩa',
          'Phường Yết Kiêu',
        ];
      case 'Sơn Tây':
        return [
          'Phường Lê Lợi',
          'Phường Ngô Quyền',
          'Phường Phú Thịnh',
          'Phường Quang Trung',
          'Phường Sơn Lộc',
          'Phường Trung Hưng',
          'Phường Trung Sơn Trầm',
          'Phường Viên Sơn',
          'Phường Xuân Khanh',
        ];
      case 'Ba Vì':
        return [
          'Thị trấn Tây Đằng',
          'Xã Ba Trại',
          'Xã Ba Vì',
          'Xã Cam Thượng',
          'Xã Cẩm Lĩnh',
          'Xã Châu Sơn',
          'Xã Chu Minh',
          'Xã Cổ Đô',
          'Xã Đông Quang',
          'Xã Đồng Thái',
          'Xã Khánh Thượng',
          'Xã Minh Châu',
          'Xã Minh Quang',
          'Xã Phong Vân',
          'Xã Phú Châu',
          'Xã Phú Cường',
          'Xã Phú Đông',
          'Xã Phú Phương',
          'Xã Phú Sơn',
          'Xã Sơn Đà',
          'Xã Tản Hồng',
          'Xã Tản Lĩnh',
          'Xã Thái Hòa',
          'Xã Thuần Mỹ',
          'Xã Tiên Phong',
          'Xã Tòng Bạt',
          'Xã Vân Hòa',
          'Xã Vạn Thắng',
          'Xã Vật Lại',
          'Xã Yên Bài',
        ];
      case 'Chương Mỹ':
        return [
          'Thị trấn Chúc Sơn',
          'Thị trấn Xuân Mai',
          'Xã Đại Yên',
          'Xã Đồng Lạc',
          'Xã Đồng Phú',
          'Xã Đông Phương Yên',
          'Xã Đông Sơn',
          'Xã Hoàng Diệu',
          'Xã Hoàng Văn Thụ',
          'Xã Hồng Phong',
          'Xã Hợp Đồng',
          'Xã Hữu Văn',
          'Xã Lam Điền',
          'Xã Mỹ Lương',
          'Xã Nam Phương Tiến',
          'Xã Ngọc Hòa',
          'Xã Ngọc Sơn',
          'Xã Phú Nam An',
          'Xã Phú Nghĩa',
          'Xã Phụng Châu',
          'Xã Quảng Bị',
          'Xã Tân Tiến',
          'Xã Thanh Bình',
          'Xã Thượng Vực',
          'Xã Thụy Hương',
          'Xã Thủy Xuân Tiên',
          'Xã Tiên Phương',
          'Xã Tốt Động',
          'Xã Trần Phú',
          'Xã Trung Hòa',
          'Xã Trường Yên',
          'Xã Văn Võ',
        ];
      case 'Đan Phượng':
        return [
          'Thị trấn Phùng',
          'Xã Đan Phượng',
          'Xã Đồng Tháp',
          'Xã Hạ Mỗ',
          'Xã Hồng Hà',
          'Xã Liên Hà',
          'Xã Liên Hồng',
          'Xã Liên Trung',
          'Xã Phương Đình',
          'Xã Song Phượng',
          'Xã Tân Hội',
          'Xã Tân Lập',
          'Xã Thọ An',
          'Xã Thọ Xuân',
          'Xã Thượng Mỗ',
          'Xã Trung Châu',
        ];
      case 'Đông Anh':
        return [
          'Thị trấn Đông Anh',
          'Xã Bắc Hồng',
          'Xã Cổ Loa',
          'Xã Dục Tú',
          'Xã Đại Mạch',
          'Xã Đông Hội',
          'Xã Hải Bối',
          'Xã Kim Chung',
          'Xã Kim Nỗ',
          'Xã Liên Hà',
          'Xã Mai Lâm',
          'Xã Nam Hồng',
          'Xã Nguyên Khê',
          'Xã Tầm Xá',
          'Xã Thụy Lâm',
          'Xã Tiên Dương',
          'Xã Uy Nỗ',
          'Xã Vân Hà',
          'Xã Vân Nội',
          'Xã Việt Hùng',
          'Xã Vĩnh Ngọc',
          'Xã Võng La',
          'Xã Xuân Canh',
          'Xã Xuân Nộn',
        ];
      case 'Gia Lâm':
        return [
          'Thị trấn Trâu Quỳ',
          'Thị trấn Yên Viên',
          'Xã Bát Tràng',
          'Xã Cổ Bi',
          'Xã Đa Tốn',
          'Xã Đặng Xá',
          'Xã Đình Xuyên',
          'Xã Đông Dư',
          'Xã Dương Hà',
          'Xã Dương Quang',
          'Xã Dương Xá',
          'Xã Kiêu Kỵ',
          'Xã Kim Lan',
          'Xã Kim Sơn',
          'Xã Lệ Chi',
          'Xã Ninh Hiệp',
          'Xã Phù Đổng',
          'Xã Phú Thị',
          'Xã Trung Mầu',
          'Xã Văn Đức',
          'Xã Yên Thường',
          'Xã Yên Viên',
        ];
      case 'Hoài Đức':
        return [
          'Thị trấn Trạm Trôi',
          'Xã An Khánh',
          'Xã An Thượng',
          'Xã Cát Quế',
          'Xã Di Trạch',
          'Xã Đắc Sở',
          'Xã Đông La',
          'Xã Đức Giang',
          'Xã Đức Thượng',
          'Xã Dương Liễu',
          'Xã Kim Chung',
          'Xã La Phù',
          'Xã Lại Yên',
          'Xã Minh Khai',
          'Xã Sơn Đồng',
          'Xã Song Phương',
          'Xã Tiền Yên',
          'Xã Vân Canh',
          'Xã Vân Côn',
          'Xã Yên Sở',
        ];
      case 'Mê Linh':
        return [
          'Thị trấn Chi Đông',
          'Thị trấn Quang Minh',
          'Xã Chu Phan',
          'Xã Đại Thịnh',
          'Xã Hoàng Kim',
          'Xã Kim Hoa',
          'Xã Liên Mạc',
          'Xã Mê Linh',
          'Xã Tam Đồng',
          'Xã Thạch Đà',
          'Xã Thanh Lâm',
          'Xã Tiền Phong',
          'Xã Tiến Thắng',
          'Xã Tiến Thịnh',
          'Xã Tráng Việt',
          'Xã Tự Lập',
          'Xã Văn Khê',
          'Xã Vạn Yên',
        ];
      case 'Mỹ Đức':
        return [
          'Thị trấn Đại Nghĩa',
          'Xã An Mỹ',
          'Xã An Phú',
          'Xã An Tiến',
          'Xã Bột Xuyên',
          'Xã Đại Hưng',
          'Xã Đốc Tín',
          'Xã Đồng Tâm',
          'Xã Hồng Sơn',
          'Xã Hợp Thanh',
          'Xã Hợp Tiến',
          'Xã Hùng Tiến',
          'Xã Hương Sơn',
          'Xã Lê Thanh',
          'Xã Mỹ Thành',
          'Xã Phù Lưu Tế',
          'Xã Phúc Lâm',
          'Xã Phùng Xá',
          'Xã Thượng Lâm',
          'Xã Tuy Lai',
          'Xã Vạn Kim',
          'Xã Xuy Xá',
        ];
      case 'Phú Xuyên':
        return [
          'Thị trấn Phú Minh',
          'Thị trấn Phú Xuyên',
          'Xã Bạch Hạ',
          'Xã Châu Can',
          'Xã Chuyên Mỹ',
          'Xã Đại Thắng',
          'Xã Đại Xuyên',
          'Xã Hoàng Long',
          'Xã Hồng Minh',
          'Xã Hồng Thái',
          'Xã Khai Thái',
          'Xã Minh Tân',
          'Xã Nam Phong',
          'Xã Nam Triều',
          'Xã Phú Túc',
          'Xã Phú Yên',
          'Xã Phúc Tiến',
          'Xã Phượng Dực',
          'Xã Quang Lãng',
          'Xã Quang Trung',
          'Xã Sơn Hà',
          'Xã Tân Dân',
          'Xã Thụy Phú',
          'Xã Tri Thủy',
          'Xã Tri Trung',
          'Xã Văn Hoàng',
          'Xã Văn Nhân',
          'Xã Vân Từ',
        ];
      case 'Phúc Thọ':
        return [
          'Thị trấn Phúc Thọ',
          'Xã Cẩm Đình',
          'Xã Hát Môn',
          'Xã Hiệp Thuận',
          'Xã Liên Hiệp',
          'Xã Long Xuyên',
          'Xã Ngọc Tảo',
          'Xã Phúc Hòa',
          'Xã Phụng Thượng',
          'Xã Sen Chiểu',
          'Xã Tam Hiệp',
          'Xã Tam Thuấn',
          'Xã Thanh Đa',
          'Xã Thọ Lộc',
          'Xã Thượng Cốc',
          'Xã Tích Giang',
          'Xã Trạch Mỹ Lộc',
          'Xã Vân Hà',
          'Xã Vân Nam',
          'Xã Vân Phúc',
          'Xã Xuân Phú',
        ];
      case 'Quốc Oai':
        return [
          'Thị trấn Quốc Oai',
          'Xã Cấn Hữu',
          'Xã Cộng Hòa',
          'Xã Đại Thành',
          'Xã Đồng Quang',
          'Xã Đông Xuân',
          'Xã Đông Yên',
          'Xã Hòa Thạch',
          'Xã Liệp Tuyết',
          'Xã Nghĩa Hương',
          'Xã Ngọc Liệp',
          'Xã Ngọc Mỹ',
          'Xã Phú Cát',
          'Xã Phú Mãn',
          'Xã Phượng Cách',
          'Xã Sài Sơn',
          'Xã Tân Hòa',
          'Xã Tân Phú',
          'Xã Thạch Thán',
          'Xã Tuyết Nghĩa',
          'Xã Yên Sơn',
        ];
      case 'Sóc Sơn':
        return [
          'Thị trấn Sóc Sơn',
          'Xã Bắc Phú',
          'Xã Bắc Sơn',
          'Xã Đông Xuân',
          'Xã Đức Hòa',
          'Xã Hiền Ninh',
          'Xã Hồng Kỳ',
          'Xã Kim Lũ',
          'Xã Mai Đình',
          'Xã Minh Phú',
          'Xã Minh Trí',
          'Xã Nam Sơn',
          'Xã Phú Cường',
          'Xã Phú Linh',
          'Xã Phú Loãng',
          'Xã Phù Lỗ',
          'Xã Phù Linh',
          'Xã Quang Tiến',
          'Xã Tân Dân',
          'Xã Tân Hưng',
          'Xã Tân Minh',
          'Xã Thanh Xuân',
          'Xã Tiên Dược',
          'Xã Trung Giã',
          'Xã Việt Long',
          'Xã Xuân Giang',
          'Xã Xuân Thu',
        ];
      case 'Thạch Thất':
        return [
          'Thị trấn Liên Quan',
          'Xã Bình Phú',
          'Xã Bình Yên',
          'Xã Cẩm Yên',
          'Xã Cần Kiệm',
          'Xã Canh Nậu',
          'Xã Chàng Sơn',
          'Xã Đại Đồng',
          'Xã Dị Nậu',
          'Xã Đồng Trúc',
          'Xã Hạ Bằng',
          'Xã Hương Ngải',
          'Xã Hữu Bằng',
          'Xã Kim Quan',
          'Xã Lại Thượng',
          'Xã Phú Kim',
          'Xã Phùng Xá',
          'Xã Tân Xã',
          'Xã Thạch Hòa',
          'Xã Thạch Xá',
          'Xã Tiến Xuân',
          'Xã Yên Bình',
          'Xã Yên Trung',
        ];
      case 'Thanh Oai':
        return [
          'Thị trấn Kim Bài',
          'Xã Bích Hòa',
          'Xã Bình Minh',
          'Xã Cao Dương',
          'Xã Cao Viên',
          'Xã Cự Khê',
          'Xã Dân Hòa',
          'Xã Đỗ Động',
          'Xã Hồng Dương',
          'Xã Kim An',
          'Xã Kim Thư',
          'Xã Liên Châu',
          'Xã Mỹ Hưng',
          'Xã Phương Trung',
          'Xã Tam Hưng',
          'Xã Tân Ước',
          'Xã Thanh Cao',
          'Xã Thanh Mai',
          'Xã Thanh Thùy',
          'Xã Thanh Văn',
          'Xã Xuân Dương',
        ];
      case 'Thanh Trì':
        return [
          'Thị trấn Văn Điển',
          'Xã Đại Áng',
          'Xã Đông Mỹ',
          'Xã Duyên Hà',
          'Xã Hữu Hòa',
          'Xã Liên Ninh',
          'Xã Ngọc Hồi',
          'Xã Ngũ Hiệp',
          'Xã Tả Thanh Oai',
          'Xã Tam Hiệp',
          'Xã Tân Triều',
          'Xã Thanh Liệt',
          'Xã Tứ Hiệp',
          'Xã Vạn Phúc',
          'Xã Vĩnh Quỳnh',
          'Xã Yên Mỹ',
        ];
      case 'Thường Tín':
        return [
          'Thị trấn Thường Tín',
          'Xã Chương Dương',
          'Xã Dũng Tiến',
          'Xã Duyên Thái',
          'Xã Hà Hồi',
          'Xã Hiền Giang',
          'Xã Hòa Bình',
          'Xã Hồng Vân',
          'Xã Khánh Hà',
          'Xã Lê Lợi',
          'Xã Liên Phương',
          'Xã Minh Cường',
          'Xã Nghiêm Xuyên',
          'Xã Nguyễn Trãi',
          'Xã Nhị Khê',
          'Xã Ninh Sở',
          'Xã Quất Động',
          'Xã Tân Minh',
          'Xã Thắng Lợi',
          'Xã Thống Nhất',
          'Xã Thư Phú',
          'Xã Tiền Phong',
          'Xã Tô Hiệu',
          'Xã Tự Nhiên',
          'Xã Văn Bình',
          'Xã Vạn Điểm',
          'Xã Văn Phú',
          'Xã Vân Tảo',
        ];
      case 'Ứng Hòa':
        return [
          'Thị trấn Vân Đình',
          'Xã Cao Thành',
          'Xã Đại Cường',
          'Xã Đại Hùng',
          'Xã Đội Bình',
          'Xã Đông Lỗ',
          'Xã Đồng Tiến',
          'Xã Đồng Tân',
          'Xã Đồng Văn',
          'Xã Hòa Lâm',
          'Xã Hòa Nam',
          'Xã Hòa Phú',
          'Xã Hoa Sơn',
          'Xã Hòa Xá',
          'Xã Hồng Quang',
          'Xã Kim Đường',
          'Xã Liên Bạt',
          'Xã Lưu Hoàng',
          'Xã Minh Đức',
          'Xã Phù Lưu',
          'Xã Phương Tú',
          'Xã Quảng Phú Cầu',
          'Xã Sơn Công',
          'Xã Tảo Dương Văn',
          'Xã Trầm Lộng',
          'Xã Trung Tú',
          'Xã Trường Thịnh',
          'Xã Vạn Thái',
          'Xã Viên An',
          'Xã Viên Nội',
        ];
      default:
        return [];
    }
  }
} 