// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8_svl5d9r2PaWnyRD9EH1x3482Lui9c',
    appId: '1:517502393576:web:d95ac2f27963c7965efd5d',
    messagingSenderId: '517502393576',
    projectId: 'campgo-project',
    authDomain: 'campgo-project.firebaseapp.com',
    storageBucket: 'campgo-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3DXUL5ur7cVIDVSkQeescluxktLqQ2Mk',
    appId: '1:517502393576:android:f16759205fdaddbc5efd5d',
    messagingSenderId: '517502393576',
    projectId: 'campgo-project',
    storageBucket: 'campgo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zJEaDRrciaRf5YSc2l2ERWfe40VgUo4',
    appId: '1:517502393576:ios:ffb925941aac01615efd5d',
    messagingSenderId: '517502393576',
    projectId: 'campgo-project',
    storageBucket: 'campgo-project.firebasestorage.app',
    iosBundleId: 'com.example.CampGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zJEaDRrciaRf5YSc2l2ERWfe40VgUo4',
    appId: '1:517502393576:ios:b5392978cae9fe425efd5d',
    messagingSenderId: '517502393576',
    projectId: 'campgo-project',
    storageBucket: 'campgo-project.firebasestorage.app',
    iosBundleId: 'com.example.campGoFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8_svl5d9r2PaWnyRD9EH1x3482Lui9c',
    appId: '1:517502393576:web:c0ee3f5a386d44115efd5d',
    messagingSenderId: '517502393576',
    projectId: 'campgo-project',
    authDomain: 'campgo-project.firebaseapp.com',
    storageBucket: 'campgo-project.firebasestorage.app',
  );
}
